### ISSUE TITLE
[backend] signup is working, with error

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#197]
```
username : user10
Nickname : John
Email : swpp@snu.ac.kr
password: asdfasdf
password confirm: asdfasdf
```

in terminal:
```
[13/Dec/2019 04:22:36] "POST /api/signup/ HTTP/1.1" 409 0
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52018)
Traceback (most recent call last):
  File "/Users/lightb0x/.pyenv/versions/3.6.9/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/lightb0x/.pyenv/versions/3.6.9/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/lightb0x/.pyenv/versions/3.6.9/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/Users/lightb0x/Documents/workspace/swpp_project/ls/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/Users/lightb0x/Documents/workspace/swpp_project/ls/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/Users/lightb0x/.pyenv/versions/3.6.9/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
----------------------------------------
```

로컬에서 테스트했고 겹치지 않는 유저네임이랑 닉네임 등 해도 에러는 같게 출력됩니다.

그리고 프론트엔드 코드를 조금 바꾸긴 했는데, 에러 이후에 `http://localhost:3000/signup?`로 리다이렉트(새로고침) 됩니다.

코드 어디에도 스트링 상태의 `?`는 없고 `signup`관련해서 `window.location.reload` 같은것도 없는데 왜그런지 알 수가 없습니다

**Comment by ulgal** [comment]
ConnectionResetError의 경우에는 내부 로직에 의한 에러가 아니라 frontend에서 request를 보내고 나서 생기는 에러같은데요?
현재 서버에 signup한 결과
```
[pid: 31774|app: 0|req: 12/12] 127.0.0.1 () {56 vars in 1104 bytes} [Fri Dec 13 04:29:13 2019] POST /api/signup/ => generated 0 bytes in 410 msecs (HTTP/1.0 201) 6 headers in 342 bytes (1 switches on core 0)
```
정상적으로 반환합니다.
아마 고치신 코드중에 문제가 있거나 코드들이 nginx에 맞춰져있어서 생긴 문제같네요.

**Comment by ulgal** [comment]
지금 에러나는 branch 올려보시면 확인해볼게요

**Comment by lightb0x** [comment]
merged to master #198
